### ISSUE TITLE
Can this be used to transfer to forge servers?

### ISSUE THREAD

**Issue by Zilacon** [Phoenix616/VersionConnector#3]
I have an issue with players... Finding their way to the correct modpack server they are on.
I was wondering if this could transfer them to the server with the correct mod id list for their client?
When a client pings a modded server on bungeecord the bungeecord sends the servers mods list to the client to show the green checkmark that its a compatible server (atleast ours does). I was hoping this could be used to send the player to the correct modpack server when they join our HUB.

And would it support transfering them to mc versions 1.4.7, 1.5.2, and 1.6.4?
Im also available on discord if you'd like to have a chat there. Zilacon#4731

Thanks.

**Comment by Phoenix616** [comment]
Yes it can be used to transfer forge clients to forge servers by using the forge section but unfortunately it can't support any version before 1.7.2 (for two reasons: the protocol IDs were changed in that version and Bungee doesn't even support it. Lower versions would require special support for whatever Bungee fork/plugin you use for sucn old versions. Also afaik one can't detect forge clients below 1.7.2)

**Comment by Zilacon** [comment]
Our bungeecord supports 1.4.7-1.14.4 minecraft versions. And supports both forms of MC protocols, and pre and post netty networking. As well as individual forge server support.

The mod id list is gathered by the bungeecord itself no matter what version the server is on. So if the bungeecord gathers that information, would this be something the plugin could pull off on our bungeecord?

**Comment by Phoenix616** [comment]
Well if you link your fork I can see how to make it compatible (or you can just PR compatibility I guess). The main issue is that you have duplicate protocol numbers so a concept for different protocol types would need to be added to the plugin.

And regarding forge detection: As long as ProxiedPlayer#isForgeUser returns the appropriate value the plugin can pick up on it.

**Comment by Zilacon** [comment]
https://github.com/fewizz/BungeeCord

**Comment by Phoenix616** [comment]
Uh, it would be a lot easier if this was a real github fork/patched one. Also not using a different maven artifact or providing a rope will make it pretty difficult to add support in any kind as you can't depend on the same artifact from two different repositories. I mean fell free to try to add support yourself but I will probably not bother as long as it's that difficult to setup.

**Comment by Zilacon** [comment]
Well we couldn't just patch bungee it had to be rebuilt completely.

**Comment by Phoenix616** [comment]
That doesn't make much sense, Waterfall uses patches as well as a separate artifact just fine.
